config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  root 'home#index'
  resources :goals do
    member do
      patch :completed
      post :encourage
    end
  end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get 'admin', to: 'admin#index'
  get "home/index"

end

app/views/shared/_relationstats.html.erb
<% @user ||= current_user %>
<div class="panel panel-default" style="margin-top: 50px">
	<div class="panel-heading">
	<strong id="following" class="relationstats">
		<%= link_to "Following", following_user_path(@user) %>
		<span class="badge"><%= @user.followed_users.count %></span>
		<%= link_to "List All", following_user_path(@user), class: "pull-right" %>
		<br>
	</strong>
	</div>
	<div class="panel-body">
		<% if @user.followed_users.any? %>
      		<% @followed_users.each do |user| %>
      			<% if user.profile %>
	      			<% if user.profile.profileimage.url == nil %>
								<%= link_to "#{user.profile.initials}", profile_path(user.profile), class: "initials" %>
	      			<% else %>
	      				<%= link_to (cl_image_tag(user.profile.profileimage, :default_image => "avatar.png", :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max)), profile_path(user.profile) %>
	      			<% end %>
      			<% else %>
      				<%= user.email %>
      			<% end %>
      		<% end %>
      	<% end %>
	</div>
	<div class="panel-heading">
	<strong id="followed" class="relationstats">
		<%= link_to "Followers", followers_user_path(@user) %>
		<span class="badge"><%= @user.followers.count %></span>
		<%= link_to "List All", followers_user_path(@user), class: "pull-right" %>
		<br>
	</strong>
	</div>
	<div class="panel-body">
		<% if @user.followers.any? %>
      		<% @followers.each do |user| %>
      			<% if user.profile %>
							<% if user.profile.profileimage.url == nil %>
								<%= link_to "#{user.profile.initials}", profile_path(user.profile), class: "initials" %>
							<% else %>
								<%= link_to (cl_image_tag(user.profile.profileimage, :default_image => "avatar.png", :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max)), profile_path(user.profile) %>
		      		<% end %>
      			<% else %>
      				<%= user.email %>
      			<% end %>
      		<% end %>
      	<% end %>
	</div>
</div>

app/views/shared/_usersearch.html.erb
<div class="search">
    <%= form_tag(profiles_path, method: :get, id: "search-form") do %>
        <div class="searchbar">
          	<%= text_field_tag :search, params[:search], placeholder: "Search Users", class: "form-control"%>
        </div>

        <button type="submit" class="btn btn-default"><% submit_tag "Search", :name => nil %>Search</button>
    <% end %>
</div>