config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  root 'home#index'
  resources :goals do
    member do
      patch :completed
      post :encourage
    end
  end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get 'admin', to: 'admin#index'
  get "home/index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  prepend_before_action :admin_pass, only:[:index]

  # GET /contacts
  # GET /contacts.json
  def index
    
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new

    if params[:filter]
      if params[:filter] == "feedback"
        @enquiry_type = "Goalkeeper Feedback"
      end
    end
  end

  # GET /contacts/1/edit
  def edit
  end


  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.received(@contact.id).deliver_now
        ContactMailer.response(@contact.id).deliver_now
        format.html { redirect_to @contact, notice: 'You enquiry has been sent.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:fname, :lname, :email, :title, :text)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :fname, label: "First Name", input_html: { value: current_user.profile.fname } %>
  	<%= f.input :lname, label: "Last Name", input_html: { value: current_user.profile.lname } %>
  	<%= f.input :email, input_html: { value: current_user.email } %>
    <%= f.input :title, label: "Subject", input_html: { value: @enquiry_type } %>
    <%= f.input :text, label: "Message" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Send" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.title %></td>
        <td><%= contact.text %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Send you're enquiry or give some feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Thanks <%= @contact.fname %>!</h2>
<p>
  <strong>Subject:</strong>
  <%= @contact.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.text %>
</p>
<%= link_to 'Back', home_index_path %>