config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  root 'home#index'
  resources :goals do
    member do
      patch :completed
      post :encourage
    end
  end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get 'admin', to: 'admin#index'
  get "home/index"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user
	has_many :encouragements

	# default_scope -> { order(updated_at: :desc) }
	# scope :desc, -> { order("goals.completed_at DESC") }
	validates :startdate, :enddate, :name, presence: true

	# validate :starts_in_future
	# validate :start_before_ends

	def self.future_events
		where("starts > ?", DateTime.current.beginning_of_day)
	end

	def start_before_ends
		if enddate.present?
			if startdate > enddate
				errors.add(:enddate, "End date can't be earlier than the start date")
			end
		else
			errors.add(:enddate, "Your goal needs an end date.")
		end
	end

	def starts_in_future
		if startdate.present? && startdate <= DateTime.current.beginning_of_day
			errors.add(:startdate, "Start date can't be before the current date")
		end
	end

	def self.order_created
		order(created_at: :desc)
	end

	def self.order_updated
		order(updated_at: :desc)
	end

	def self.order_completed
		order(completed_at: :desc)
	end

	def self.completed
		where(complete: true)
	end

	def self.incomplete
		where(complete: false)
	end

	def self.last7
    	where("completed_at >= ? ", 7.days.ago)
	end

	def self.previous_week
	  	where(completed_at: DateTime.current.beginning_of_day - 7.days..DateTime.current.beginning_of_day - 14.days)
	end

	def self.complete_before_enddate
		where("complete = true AND completed_at <= enddate")
	end

	def percent_of(n)
    	self.to_f / n.to_f * 100.0
  	end


	# def self.last_12_months
	# 	where(range = (DateTime.now.beginning_of_month - 11.months)..DateTime.now.end_of_month)
	# end



end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:completed, :show, :edit, :update, :destroy, :encourage]



  def completed
    @goal.update_attributes(:complete => true, :completed_at => DateTime.now.beginning_of_day)
    redirect_to :back
  end

  def encourage
    @encourage = Encouragement.create!(user: current_user, goal: @goal)
    if @encourage.save
      # EncouragementMailer.encouragement_received(current_user, @goal.id).deliver_now
    else
      flash[:warning] = "It's broken, you didn't really want to do that."
    end
  end

  # GET /goals
  # GET /goals.json
  def index
    @goals = current_user.goals
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goals = current_user.goals
  end

  # GET /goals/new
  def new
    @goal = Goal.new
    @goals = current_user.goals.order_created
  end

  # GET /goals/1/edit
  def edit
    @goals = current_user.goals
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @goals = current_user.goals
    respond_to do |format|
      if @goal.save
        format.html { redirect_to home_index_path, notice: 'Goal was successfully created.' }
        # format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, notice: "There was an error updating your goal." }
        # format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    @goals = current_user.goals
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to home_index_path, notice: 'Goal was successfully updated.' }
        # format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, notice: 'There was an error updating your goal.' }
        # format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:user_id, :startdate, :enddate, :name, :details, :complete, :completed_at)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper

end

app/views/goals/_form.html.erb
<%= simple_form_for(@goal, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :startdate, label: "Goal Starts", as: :date, discard_time: true %>
    <%= f.input :enddate, label: "Goal Ends", as: :date, discard_time: true %>
    <%= f.input :name, input_html: { class: "form-control form-1" } %>
    <%= f.input :details, as: :text, input_html: { class: "form-control form-1" } %>
    <%= f.input :complete, label: "Have you completed this goal?", as: :boolean %>
  </div>
    <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<p class="noticetext" id="notice"><%= notice %></p>

<!-- scripts -->

<script type="text/javascript">
$(document).ready(function() {
  $('#datepicker').datepicker({
    format: 'dd/mm/yyyy'
}
});
</script>

app/views/goals/_goal.html.erb
<div class="panel panel-default">
			<div class="panel-body">
				<% if current_user.profile == @profile %>
					<div class="col-md-10">
						<h4><strong><%= goal.name %></strong></h4>
						<p><strong>Starts </strong><%= goal.startdate.strftime("%v") %>  <strong>Ends </strong><%= goal.enddate.strftime("%v") %></p>
						<p><%= goal.details %></p>
							<%= link_to 'Edit', edit_goal_path(goal), method: :get %> |
							<%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
					<div class="col-sm-2">
						<div class="text-center">
							<% if goal.complete %>
								<h4 class="orgtxt"><strong><%= "Complete!" %></strong></h4>
								<p><%= goal.completed_at.strftime("%v") if goal.completed_at %></p>
							<% else %>
								<%= link_to "Complete", completed_goal_path(goal), method: :patch, class: "btn btn-warning" %>
							<% end %>
						</div>
					</div>

				<% else %>
					<div class="col-md-10">
						<h4><strong><%= goal.name %></strong></h4>
						<p><strong>Starts </strong><%= goal.startdate.strftime("%v") %>  <strong>Ends </strong><%= goal.enddate.strftime("%v") %></p>
						<p><%= goal.details %></p>

					<%= render "encouragements/give_encouragement", goal: goal%>

					</div>
					
					<div class="col-sm-2">
						<div class="text-center">
							<% if goal.complete %>
								<br>
								<h4 class="orgtxt"><strong>Complete!</strong></h4>
								<p><%= goal.completed_at.strftime("%v") if goal.completed_at %></p>
							<% else %>
								<br>
								<h4><%= "Not Complete" %></h4>
							<% end %>
						</div>
					</div>
				<% end %>

			</div>
</div>

app/views/goals/_goalfeed.html.erb
<div class="tab-content">


	<ul class="nav nav-tabs" role="tablist">
	    <li role="presentation" class="active"><a href="#myFeed" aria-controls="myFeed" role="tab" data-toggle="tab">My Goals</a></li>
	    <li role="presentation"><a href="#goalFeed" aria-controls="goalFeed" role="tab" data-toggle="tab">Feed</a></li>
	</ul>


	<div role="tabpanel" class="tab-pane fade in active" id="myFeed">
		<h2>My Goals</h2>

			<%= link_to "New Goal", new_goal_path, method: :get, class: "btn btn-warning" %>
		<div class="pull-right">
			<%= link_to "Complete", home_index_path(filter: 'complete'), method: :get %> |
			<%= link_to "Incomplete", home_index_path(filter: 'incomplete'), method: :get %> |
			<%= link_to "All", home_index_path, method: :get %>
		</div>
		<!-- <div class="pull-right"> -->
			<%# link_to "Complete", @profile.user.goals.complete %>

		<div class="feed">
			<%= render @goals %>
		</div>
		<%# will_paginate @goals %>

	</div>

	<div role="tabpanel" class="tab-pane fade in" id="goalFeed">
		<h2>Feed</h2>
			<div>
				<% @feed_items.each do |goal| %>
					<div class="panel panel-default">
						<div class="panel-body">
							<div class="col-sm-10">
								<h4><strong><%= goal.name %></strong></h4>
								<p>
								<% if goal.user.profile %>
				      				<%= goal.user.profile.name %>
				      			<% else %>
				      				<%= goal.user.email %>
				      			<% end %>
				      			</p>
								<p><strong>Starts </strong><%= goal.startdate.strftime("%v") %>  <strong>Ends </strong><%= goal.enddate.strftime("%v") %></p>
								<p><%= goal.details %></p>

									<%= render "encouragements/give_encouragement", goal: goal%>

							</div>

							<div class="col-sm-2">
								<div class="text-center">
									<% if goal.user.profile %>
										<div>
											<% if goal.user.profile.profileimage.url == nil %>
												<%= link_to (cl_image_tag "avatar.png", :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max), profile_path(goal.user.profile), method: :get %>
											<% else %>
												<%= link_to (cl_image_tag(goal.user.profile.profileimage, :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max)), profile_path(goal.user.profile), method: :get %>
											<% end %>
										</div>
									<% end %>

									<% if goal.complete %>
										<br>
										<p class="orgtxt"><strong>Complete!</strong></p>
										<p class="orgtxt"><%= goal.completed_at.strftime("%v") if goal.completed_at %></p>
									<% else %>
										<br>
										<p><strong><%= "Not Complete" %></strong></p>
									<% end %>
								</div>

							</div>
						</div>
					</div>
				<% end %>
			</div>

	</div>
</div>


<!-- scripts -->

<script type="text/javascript">
	$('#myFeed a').click(function (e) {
		e.preventDefault()
		$(this).tab('show')
	})

	$('#goalFeed a').click(function (e) {
		e.preventDefault()
		$(this).tab('show')
	})
</script>

app/views/goals/_mycompgoals.html.erb
	<h3>Goal Stats</h3>
		<table>
			<tr>
				<td>Total Goals: </td>
				<td><strong><%= @goals.count %></strong></td>
			</tr>
			<!-- <tr>
				<td>Goals Complete: </td>
				<td><strong><%= @completed_goals.count %></strong></td>
			</tr> -->
			<tr>
				<td>Goals Complete: </td>
				<td><strong><%= @usergoals.count %></strong></td>
			</tr>
			<tr>
				<td>Incomplete Goals: </td>
				<td><strong><%= @incomplete_goals.count %></strong></td>
			</tr>
			<tr>
				<td>Last 7 Days: </td>
				<td><strong><%= @completed_goals.last7.count %></strong></td>
			</tr>
			<tr>
				<td>Previous 7 Days: </td>
				<td><strong><%= @completed_goals.previous_week.count %></strong></td>
			</tr>
			<tr>
				<td><h4><a href="#GoalScoreModal" data-toggle="modal">Goal Score</a></h4></td>
				<td>
					<h4><strong>
						<% if @completed_goals.any? %>
							<%= ((@complete_before_enddate.count.to_f / @usergoals.count.to_f) * 10).to_i %>
						<% else %>
							<%= 0 %>
						<% end %>
					</strong></h4>
					</td>
		</table>

<!-- Modal -->
<div class="modal fade" id="GoalScoreModal" tabindex="-1" role="dialog" aria-labelledby="GoalScoreModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="GoalScoreModalLabel">Goal Score</h4>
      </div>
      <div class="modal-body">
        <p>Your Goal Score is an analysis of your completed goals. It gives you feedback on your goal completion within the time period set for the goal. Goal Score is rated from 0 to 10. </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/goals/_mygoals.html.erb
<h1>My Goals</h1>
<p><%= link_to 'New Goal', new_goal_path, class: "pull-right" %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Name</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.startdate.strftime("%v") %></td>
        <td><%= goal.enddate.strftime("%v") %></td>
        <td><%= goal.name.truncate(20) %></td>
        <td><%= goal.complete %></td>
        <td><%= link_to 'Details', goal %></td>
        <td><%= link_to 'Edit Goal', edit_goal_path(goal) %></td>
        <td><%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/goals/edit.html.erb
<h1>Edit Your Goal</h1>
<%= link_to 'Back', home_index_path %>
<br>
<div class="col-md-4 formp" >
	<%= render 'form' %>
</div>

<div class="col-md-8 feedborder">
<h2>Current Goals</h2>
	<%= render @goals %>
</div>

app/views/goals/encourage.js.erb
$("#encouragement_for_goal_<%= @goal.id %>").replaceWith("<%= escape_javascript(render('encouragements/give_encouragement', goal: @goal)) %>");
// $("#encouragement_for_goal_<%= @goal.id %>").hide();
// $("#encouragement_for_goal_<%= @goal.id %>").shake();
$("#encouragement_for_goal_<%= @goal.id %>").effect( "bounce", "slow" );

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Goals</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Name</th>
      <th>Details</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.startdate.strftime("%v") %></td>
        <td><%= goal.enddate.strftime("%v") %></td>
        <td><%= goal.name %></td>
        <td><%= goal.details %></td>
        <td><%= goal.complete %></td>
        <td><%= link_to 'Details', goal %></td>
        <td><%= link_to 'Edit Goal', edit_goal_path(goal) %></td>
        <td><%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Goal', new_goal_path %></p>
<p><%= link_to "Home", home_index_path %></p>

app/views/goals/new.html.erb
<h1>Create a New Goal</h1>
<%= link_to 'Back', home_index_path %>
<br>
<div class="col-md-4 formp">
	<%= render 'form' %>
</div>

<div class="col-md-8 feedborder">
<h2>Current Goals</h2>
	<%= render @goals %>
</div>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Startdate:</strong>
  <%= @goal.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @goal.enddate %>
</p>

<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @goal.details %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @goal.complete %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', home_index_path %>