config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  root 'home#index'
  resources :goals do
    member do
      patch :completed
      post :encourage
    end
  end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get 'admin', to: 'admin#index'
  get "home/index"

end

app/views/layouts/_footer.html.erb
<footer>

	<!-- <div class="navbar navbar-default" role="navigation"> -->
		<div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 text-center">
					<% if user_signed_in? %>
						<h4><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp <%= link_to "Contact", new_contact_path %>  |  
						<span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp <%= link_to "Feedback", new_contact_path(filter: "feedback") %></h4>
					<% end %>
					</div>
					<div class="col-sm-4 text-center">
						<h4>Goalkeeper</h4>
					</div>
					<div class="col-sm-4">
						<p><strong>This app is in beta, there will be bugs!</strong></p>
						<p>If you like this app let me know. If you don't like it also let me know and tell me how I could make it more suited to you.</p>
					</div>
				</div>
			</div>
		</div>
	<!-- </div> -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= home_index_path %>"><%= cl_image_tag "GOALKEEPER.png", :height => 25 %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to " ", new_goal_path, class: "glyphicon glyphicon-plus" %></li>
          <% if current_user.profile %>
            <li><%= link_to "Goal Feed", home_index_path %></li>
            <li><a href="<%= home_index_path(filter: 'incomplete') %>"><span class="badge"><%= current_user.goals.incomplete.count %></span></a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-target="#" href="<%= profile_path(current_user.profile) %>" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= user_nav_avatar %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Profile", profile_path(current_user.profile) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        <% else %>
                  <li><%= link_to "Sign In", new_user_session_path %>
                </ul>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Scripts -->
<script type="text/javascript">
  $('.dropdown').hover(function(){
  $('.dropdown-toggle', this).trigger('click');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goalkeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />

  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

  <!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->

<!-- Optional theme -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"> -->

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<!-- jQuery -->
<!-- <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script> -->

</head>
  <body>

    <% unless user_signed_in? %>
    	<div class="background">
    <% end %>

    	<%= render "layouts/navbar" %>

    <div class="container">
    <div class="homemargin">
    		<%= yield %>
    </div>
    </div>
    <br>
    	<%= render "layouts/footer" %>

  </body>
</html>